export interface PregnancyWeekData {
  trimester: string;
  week: number;
  development: string;
  size: string;
  procedures: string;
}

export const pregnancyData: PregnancyWeekData[] = [
  {
    trimester: "First",
    week: 1,
    development: "Conception and implantation.",
    size: "Size: 0.1-0.2 mm (zygote)",
    procedures: "Blood test (hCG levels), urine test to confirm pregnancy.",
  },
  {
    trimester: "First",
    week: 2,
    development: "Conception and implantation continue.",
    size: "Size: 0.1-0.2 mm (zygote)",
    procedures: "Blood test (hCG levels), urine test to confirm pregnancy.",
  },
  {
    trimester: "First",
    week: 3,
    development: "Blastocyst implants in the uterus; hCG production begins.",
    size: "Size: 0.1-0.2 mm.",
    procedures: "Blood test to confirm pregnancy.",
  },
  {
    trimester: "First",
    week: 4,
    development: "Positive pregnancy test; placenta begins to form.",
    size: "Size: 1-2 mm (poppy seed).",
    procedures: "Home pregnancy test; first prenatal visit scheduled.",
  },
  {
    trimester: "First",
    week: 5,
    development: "Embryo size: sesame seed; neural tube forms.",
    size: "Size: 2-3 mm (sesame seed).",
    procedures: "First prenatal visit (if not done earlier).",
  },
  {
    trimester: "First",
    week: 6,
    development: "Heartbeat begins; facial features start forming.",
    size: "Size: 4-5 mm (lentil).",
    procedures: "Dating ultrasound to confirm pregnancy and check heartbeat.",
  },
  {
    trimester: "First",
    week: 7,
    development: "Brain, eyes, and ears develop; limb buds appear.",
    size: "Size: 8-10 mm (blueberry).",
    procedures: "Blood tests (blood type, Rh factor, infections).",
  },
  {
    trimester: "First",
    week: 8,
    development: "Major organs form; embryo now called a fetus.",
    size: "Size: 1.6 cm, Weight: 1 g (raspberry).",
    procedures: "Urine test (protein, glucose, infections).",
  },
  {
    trimester: "First",
    week: 9,
    development: "Fetal movements begin; facial features become distinct.",
    size: "Size: 2.3 cm, Weight: 2 g (cherry).",
    procedures: "Genetic screening options discussed (e.g., NIPT, CVS).",
  },
  {
    trimester: "First",
    week: 10,
    development: "Critical development ends; nails and hair begin to form.",
    size: "Size: 3.1 cm, Weight: 4 g (strawberry).",
    procedures: "Nuchal translucency (NT) scan scheduled (Weeks 11-14).",
  },
  {
    trimester: "First",
    week: 11,
    development: "Rapid growth; bones begin to harden.",
    size: "Size: 4.1 cm, Weight: 7 g (lime).",
    procedures: "First-trimester screening (NT scan + blood tests for PAPP-A and hCG).",
  },
  {
    trimester: "First",
    week: 12,
    development: "Reflexes develop; fetus can make sucking movements.",
    size: "Size: 5.4 cm, Weight: 14 g (plum).",
    procedures: "Chorionic villus sampling (CVS) if needed (Weeks 10-13).",
  },
  {
    trimester: "First",
    week: 13,
    development: "Vocal cords form; risk of miscarriage decreases.",
    size: "Size: 7.4 cm, Weight: 23 g (lemon).",
    procedures: "End of first trimester; routine checkup.",
  },
  {
    trimester: "Second",
    week: 14,
    development: "Fetus can make facial expressions; fine hair (lanugo) covers the body.",
    size: "Size: 8.7 cm, Weight: 43 g (peach).",
    procedures: "Routine blood and urine tests.",
  },
  {
    trimester: "Second",
    week: 15,
    development: "Fetus can move limbs; mother may feel flutters (quickening).",
    size: "Size: 10.1 cm, Weight: 70 g (apple).",
    procedures: "Quad screen scheduled (Weeks 15-20).",
  },
  {
    trimester: "Second",
    week: 16,
    development: "Facial expressions develop; eyes are sensitive to light.",
    size: "Size: 11.6 cm, Weight: 100 g (avocado).",
    procedures: "Anatomy ultrasound scheduled (Weeks 18-22).",
  },
  {
    trimester: "Second",
    week: 17,
    development: "Fat begins to accumulate under the skin.",
    size: "Size: 13 cm, Weight: 140 g (pear).",
    procedures: "Routine checkup; discuss amniocentesis if needed.",
  },
  {
    trimester: "Second",
    week: 18,
    development: "Hearing develops; bones harden.",
    size: "Size: 14.2 cm, Weight: 190 g (sweet potato).",
    procedures: "Anatomy ultrasound to check fetal development and sex.",
  },
  {
    trimester: "Second",
    week: 19,
    development: "Vernix caseosa (protective coating) forms on the skin.",
    size: "Size: 15.3 cm, Weight: 240 g (mango).",
    procedures: "Routine blood and urine tests.",
  },
  {
    trimester: "Second",
    week: 20,
    development: "Halfway point; fetus is more active.",
    size: "Size: 16.4 cm, Weight: 300 g (banana).",
    procedures: "Glucose screening test scheduled (Weeks 24-28).",
  },
  {
    trimester: "Second",
    week: 21,
    development: "Taste buds develop; fetus can swallow amniotic fluid.",
    size: "Size: 26.7 cm, Weight: 360 g (carrot).",
    procedures: "Routine checkup.",
  },
  {
    trimester: "Second",
    week: 22,
    development: "Hair grows on the head; fetus is more active.",
    size: "Size: 27.8 cm, Weight: 430 g (spaghetti squash).",
    procedures: "Routine blood and urine tests.",
  },
  {
    trimester: "Second",
    week: 23,
    development: "Lungs develop; fetus practices breathing movements.",
    size: "Size: 28.9 cm, Weight: 500 g (grapefruit).",
    procedures: "Glucose screening test (if not done earlier).",
  },
  {
    trimester: "Second",
    week: 24,
    development: "Fetus reaches viability; could survive outside the womb with medical help.",
    size: "Size: 30 cm, Weight: 600 g (ear of corn).",
    procedures: "Rh antibody test for Rh-negative mothers.",
  },
  {
    trimester: "Second",
    week: 25,
    development: "Fetus responds to touch and sound.",
    size: "Size: 34.6 cm, Weight: 660 g (rutabaga).",
    procedures: "Routine checkup.",
  },
  {
    trimester: "Second",
    week: 26,
    development: "Eyes can open; lungs continue to mature.",
    size: "Size: 35.6 cm, Weight: 760 g (scallion).",
    procedures: "Routine blood and urine tests.",
  },
  {
    trimester: "Second",
    week: 27,
    development: "Brain activity increases; lungs continue to mature.",
    size: "Size: 36.6 cm, Weight: 875 g (cauliflower).",
    procedures: "TDAP vaccine recommended (Weeks 27-36).",
  },
  {
    trimester: "Third",
    week: 28,
    development: "Fetus can blink and dream; third trimester begins.",
    size: "Size: 37.6 cm, Weight: 1 kg (eggplant).",
    procedures: "Routine checkup; discuss birth plan.",
  },
  {
    trimester: "Third",
    week: 29,
    development: "Muscles and lungs mature; fetus gains weight.",
    size: "Size: 38.6 cm, Weight: 1.2 kg (butternut squash).",
    procedures: "Routine blood and urine tests.",
  },
  {
    trimester: "Third",
    week: 30,
    development: "Fetus gains fat; eyes can perceive light and dark.",
    size: "Size: 39.9 cm, Weight: 1.3 kg (cabbage).",
    procedures: "Ultrasound to check fetal growth and amniotic fluid levels (if needed).",
  },
  {
    trimester: "Third",
    week: 31,
    development: "Fetus can perceive light and dark; rapid brain development.",
    size: "Size: 41.1 cm, Weight: 1.5 kg (coconut).",
    procedures: "Routine checkup.",
  },
  {
    trimester: "Third",
    week: 32,
    development: "Fetus may move into a head-down position.",
    size: "Size: 42.4 cm, Weight: 1.7 kg (jicama).",
    procedures: "Group B Streptococcus (GBS) test scheduled (Weeks 35-37).",
  },
  {
    trimester: "Third",
    week: 33,
    development: "Bones harden; skull remains soft for delivery.",
    size: "Size: 43.7 cm, Weight: 1.9 kg (pineapple).",
    procedures: "Routine blood and urine tests.",
  },
  {
    trimester: "Third",
    week: 34,
    development: "Immune system develops; fetus practices breathing.",
    size: "Size: 45 cm, Weight: 2.1 kg (cantaloupe).",
    procedures: "Non-stress test (NST) or biophysical profile (BPP) if high-risk.",
  },
  {
    trimester: "Third",
    week: 35,
    development: "Lungs are nearly fully developed.",
    size: "Size: 46.2 cm, Weight: 2.4 kg (honeydew melon).",
    procedures: "GBS test performed.",
  },
  {
    trimester: "Third",
    week: 36,
    development: "Fetus gains fat; may drop lower into the pelvis.",
    size: "Size: 47.4 cm, Weight: 2.6 kg (papaya).",
    procedures: "Pelvic exam to check cervical dilation and effacement.",
  },
  {
    trimester: "Third",
    week: 37,
    development: "Fetus is considered full-term.",
    size: "Size: 48.6 cm, Weight: 2.9 kg (Swiss chard).",
    procedures: "Weekly checkups begin; NST or BPP if high-risk.",
  },
  {
    trimester: "Third",
    week: 38,
    development: "Brain and lungs are fully developed; fetus is ready for birth.",
    size: "Size: 49.8 cm, Weight: 3.1 kg (pumpkin).",
    procedures: "Routine checkup; discuss induction if overdue.",
  },
  {
    trimester: "Third",
    week: 39,
    development: "Fetus is fully developed; waiting for labor to begin.",
    size: "Size: 50.7 cm, Weight: 3.3 kg (mini watermelon).",
    procedures: "Membrane sweep offered if overdue.",
  },
  {
    trimester: "Third",
    week: 40,
    development: "Due date arrives; labor could begin any day.",
    size: "Size: 51.2 cm, Weight: 3.5 kg (small pumpkin).",
    procedures: "Final checkup; discuss induction if labor hasn’t started.",
  },
];
