[build]
  command = "npm install && npm run build:netlify"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@remix-run/*"]

# Serve static assets directly
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Serve public files directly
[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/calculator.svg"
  to = "/calculator.svg"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

# Route all other requests through the SSR function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true
